# Generated by Django 5.1.2 on 2024-11-30 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedTrade",
            fields=[
                (
                    "trade_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_address", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("market_cap", models.FloatField()),
                ("image_url", models.URLField()),
                ("price_usd", models.FloatField()),
                ("created_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                ("pnl_percentage", models.FloatField()),
            ],
        ),
    ]
